### ISSUE TITLE
Set default docker port binding IP

### ISSUE THREAD

**Issue by robholland** [nlf/dhyve-os#10]
Currently docker will bind ports to 0.0.0.0 on the VM which means that when running `docker-compose port postgres 5432` (or just using docker inspect) we get back `0.0.0.0:<bound port>`. This means that I need to replace the `0.0.0.0` with the VM's IP in order to use it, putting back some of the pain that DLite might otherwise save.

It would be very useful if `--ip=192.168.x.x` was passed to the docker daemon when starting so that it would by default bind ports to the interface that we can reach from outside the VM. This way docker inspect and docker-compose would show an `IP:PORT` combination that can be connected to as-is.

That way I never have to care what the IP address of the VM is.

**Comment by nlf** [comment]
this is a good idea, i'll sort it out and make it work. thanks!

**Comment by robholland** [comment]
$ dc port dbtest 5432
192.168.64.4:32768

:+1:
