### ISSUE TITLE
Build takes a very long time then fails...

### ISSUE THREAD

**Issue by pfortin-urbn** [nlf/dhyve-os#17]
I tried build dhyve-os to support our enterprise but it has been running now for over 55 mins is this normal?

it's seems stuck here...

> > > linux 4.3.3 Configuring
> > > linux 4.3.3 Building
> > > ...

finally it continued then I got this and it failed:

cc1: some warnings being treated as errors
scripts/Makefile.modpost:113: recipe for target 'net/ipv4/netfilter/arptable_filter.mod.o' failed
make[2]: **\* [net/ipv4/netfilter/arptable_filter.mod.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
Makefile:1095: recipe for target 'modules' failed
make[1]: **\* [modules] Error 2
package/pkg-generic.mk:196: recipe for target '/tmp/buildroot/output/build/linux-4.3.3/.stamp_built' failed
make: **\* [/tmp/buildroot/output/build/linux-4.3.3/.stamp_built] Error 2
make: **\* [build] Error 2

**Comment by nlf** [comment]
It is a pretty slow build, and yes that's expected. The failure at the end isn't. How much free memory does your docker host have? I generally give it at least 3GB

**Comment by pfortin-urbn** [comment]
I did not change the settings from the standard dlite - the second time I ran it, it completed successfully
