### ISSUE TITLE
Instead of replacing the existing image, can we update the version even for pre-releases?

### ISSUE THREAD

**Issue by akatrevorjay** [nlf/dhyve-os#22]
I see that 3.0.0 has been replaced a few times now, can we bump the version each time so I know if I'm out of date?

Sorry to be a pest, lol.

Ty,
Trevor

**Comment by nlf** [comment]
yeah, i probably should be lol. i'll start adding -beta tags to the versions

**Comment by akatrevorjay** [comment]
You're the man! Thank you!
