### ISSUE TITLE
docker fetch throws 403

### ISSUE THREAD

**Issue by SerialVelocity** [nlf/dhyve-os#27]
Hey,

getting docker from `https://get.docker.io/builds/Linux/x86_64/docker-${docker_version}` no longer works. It throws a 403. If you add `.tgz` on the end however it works. You can run this through gunzip then tar to get the binaries.

Since the overlay size wasn't big enough to hold all the files. I put `docker` in `/usr/bin/` and `docker-*` in `/bin/`

Cheers,
Ben

**Comment by nlf** [comment]
yup. already working on a fix

**Comment by SerialVelocity** [comment]
@nlf Can we merge a temporary fix for now?

**Comment by nlf** [comment]
version 2.3.0 of the OS has this fix in place
