### ISSUE TITLE
0-byte docker binary in dhyve os 3.0.0-beta4

### ISSUE THREAD

**Issue by mhubig** [nlf/dhyve-os#29]
It seems the `rootfs/etc/init.d/S51docker` script is overwriting the docker binary on startup with a 0-byte file.

**Comment by nlf** [comment]
the master branch (which supports the beta of dlite 2.0) already has this fixed, but is in huge amounts of flux right now, so there won't be another release until i'm finished with the refactoring. for now if you're continuing to use the beta i would suggest sticking to docker 1.10
