### ISSUE TITLE
make the makefile better

### ISSUE THREAD

**Issue by nlf** [nlf/dhyve-os#3]
i don't like how it is now, it needs to be better. i hate that i have to run `make build` manually if i change files and then `make` again to get the artifacts out of it.

maybe it's best to just build everything in the image and then create a container without running it to extract the artifacts?

**Comment by nlf** [comment]
the main concern i have is to make repeated builds faster (as in don't redownload and recompile the entire tree if we don't have to), which is why the dl and ccache directories are volumes and the building is done at runtime instead of compile time.

not the best solution though, so i'm definitely up for suggestions.

**Comment by ailispaw** [comment]
Yeah. rancher/os-base does so (everything in an image and create/cp).
https://github.com/rancher/os-base/blob/master/build.sh

But I'm thinking ON_BUILD and another Dockerfile to build.

**Comment by nlf** [comment]
that's an interesting thought. care to try implementing it and submit a pull request?

**Comment by ailispaw** [comment]
Just an idea now.

**Comment by ailispaw** [comment]
BTW, I would like to try the new dhyve with DhyveOS first though.

**Comment by nlf** [comment]
i'm working on getting dhyve updated to use dhyveos right now :) should be usable shortly.

**Comment by ailispaw** [comment]
@nlf Thanks. Looking forward to it.

**Comment by nlf** [comment]
i'm pretty ok with the makefile now, closing this
