### ISSUE TITLE
overlayfs causes problems with yum -- can we use a different storage driver?

### ISSUE THREAD

**Issue by amcinnes** [nlf/dhyve-os#6]
dhyve-os currently uses the overlay storage driver, which has a known issue that causes `yum` to fail in containers. (Documented in https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/)

Would it be reasonable to support and default to a different storage driver, such as AUFS or devicemapper?

**Comment by nlf** [comment]
definitely reasonable, it's actually been on my list of things to work out for a while now. i'll see what i can do.

**Comment by nlf** [comment]
i revamped everything and made a pre-release of a new version using devicemapper for storage [here](https://github.com/nlf/dhyve-os/releases/tag/v2.0.0)

please do check it out and let me know if you have any issues. i've been using it myself for a day or so now and it seems to be pretty stable.

note that you'll have to download it manually (i set it as a pre-release so as not to release it to the wild just yet)

**Comment by amcinnes** [comment]
Yeah, it seems to have resolved this issue. Thanks! :)

**Comment by nlf** [comment]
i'm actually going to shift gears and use btrfs instead, i think. it makes for a smaller overall download and is a lot simpler to configure to work reliably

**Comment by clkao** [comment]
Hi @nlf, I think you forgot to push what's in the v2.0.0 tag to master.

**Comment by nlf** [comment]
appears to be pushed on my end, what do you think is missing?

**Comment by clkao** [comment]
This is what I see: (v2.0.0 is ahead of current master, which is 2d1db57)

```
* c61d125 - (tag: v2.0.0) switch to btrfs (Sat, 16 Jan 2016 11:15:28 -0800, Nathan LaFreniere)
*   2d1db57 - (HEAD -> master, origin/master, origin/HEAD) merge (Fri, 1 Jan 2016 14:44:08 -0800, Nathan LaFreniere)
|\
| *   67504db - Merge pull request #8 from nlf/date_format (Sat, 26 Dec 2015 22:02:13 -0800, Nathan LaFreniere)
| |\
| | * 60a6e10 - Date format in docker inspect has been changed (Sun, 27 Dec 2015 13:47:46 +0900, A.I)
| |/
* | 2e212ad - total revamp of build system, switch to devicemapper for storage (Fri, 1 Jan 2016 14:43:17 -0800, Nathan LaFrenier
|/
* a7fe915 - (tag: v1.5.0) switch to non-snapshot buildroot, update buildroot and kernel configs (Fri, 11 Dec 2015 13:42:19 -0800
```

**Comment by nlf** [comment]
right you are.. i apparently hadn't pushed. just did
