### ISSUE TITLE
Increase default ulimit

### ISSUE THREAD

**Issue by jakajancar** [nlf/dhyve-os#9]
The default docker Debian package sets

```
ulimit -n 1048576
if [ "$BASH" ]; then
        ulimit -u 1048576
else
        ulimit -p 1048576
fi  
```

DhyveOS has much smaller limits, and although they can be changed using `--ulimit` when doing `docker run`, this causes some images that work using the Debian docker to fail with DyhveOS. It would be cool if these limits could be increased.

**Comment by nlf** [comment]
good call, they should definitely be raised
